# Assignment 8

- Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
# function to add two matrices :
def add(arr1, arr2):
    return np.add(arr1, arr2)

- Write a Python Program to Multiply Two Matrices?

In [2]:
# function to Multiply two matrices :
def mult(arr1, arr2):
    return np.multiply(arr1, arr2)

- Write a Python Program to Transpose a Matrix?

In [12]:
# function for converting matrics as transpose matrics :
def transpose(arr):
    return arr.T

- Write a Python Program to Sort Words in Alphabetic Order?

In [17]:
def alpha_sort(arr):
    arr.sort()
    for i in arr:
        print

- Write a Python Program to Remove Punctuation From a String?

In [6]:
def remove_punc(s):
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for i in s:
        if i in punc:
            s = s.replace(i, "")
    return s

# Solution :

## 1 :

In [7]:
# Creating two matrix using numpy library:
x = np.array([[1,2,3],[2,3,4],[3,4,5]])
y = np.array([[2,3,4],[3,4,5],[4,5,6]])

In [8]:
add(x,y)

array([[ 3,  5,  7],
       [ 5,  7,  9],
       [ 7,  9, 11]])

## 2:

In [9]:
mult(x,y)

array([[ 2,  6, 12],
       [ 6, 12, 20],
       [12, 20, 30]])

## 3 :

In [15]:
n = np.array([[2,3,34],[23,232,1],[2,32,11]])
print(n)
print(" - "*30)
print(transpose(n))

[[  2   3  34]
 [ 23 232   1]
 [  2  32  11]]
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - 
[[  2  23   2]
 [  3 232  32]
 [ 34   1  11]]


## 4 :

In [19]:
print(alpha_sort(["mango","banana","grapes","apple"]))

None


## 5 :

In [22]:
#This function remove all  Punctuation and return new string :
s = input("Enter new String with  Punctuation :- ")
print(remove_punc(s))

Enter new String with  Punctuation :- This is, new function? that will>< reduce every! things,
This is new function that will reduce every things
